### ISSUE TITLE
Add support for running the systemd as non-root user & add extra ExecStartPre/Post

### ISSUE THREAD

**Issue by Adito5393** [Mikroways/ansible_restic#1]
I plan to make some changes to the role:

1. Run restic as non-root, following the [docs recommendations](https://restic.readthedocs.io/en/stable/080_examples.html#backing-up-your-system-without-running-restic-as-root). I don't plan to create the user within this role.
2. Add `ExecStartPre=` & `ExecStartPost=` to the systemd_service.unit as a list of commands that a user can pass as a list. If the user calls a bash file, then this should already be available on the system (with the correct permissions).
3. Add the ability to set GOMAXPROCS: https://github.com/arillso/ansible.restic/issues/109

Would you be interested in a PR?

PS: I have little experience with python & zero with tox. However, I think I can implement it & learn from the review process.

**Comment by chrodriguez** [comment]
Thanks for your suggestions. Please go ahead with a PR, it'll be very welcome

**Comment by chrodriguez** [comment]
Thanx @Adito5393
